heat_template_version: 2013-05-23

description: >
  HOT template to add more hosts to node.consul 
  infrastructure, Note: THIS DEPENDS ON iac_base

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image_linux:
    type: string
    description: Name of image to use for Linux server
  image_windows_server:
    type: string
    description: Name of image to use for Windows server
  image_windows_client:
    type: string
    description: Name of image to use for Windows client
  sec_group_linux:
    type: comma_delimited_list
    description: Security groups
  sec_group_windows_server:
    type: comma_delimited_list
    description: Security groups
  sec_group_windows_client:
    type: comma_delimited_list
    description: Security groups
  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
  admin_net:
    type: string
    description: UUID of admin net created in base template (iac_admin_net)
  admin_subnet:
    type: string
    description: UUID of admin subnet created in base template (192.168.180.0/24)
  manager_ip:
    type: string
    description: IP address of server manager created in base template

resources:

  dir:
    type: lib/managed_linux_server.yaml
    properties:
          key_name:          { get_param: key_name }
          server_name:       dir
          image:             { get_param: image_linux }  
          flavor:            m1.tiny
          sec_group_linux:   { get_param: sec_group_linux }  
          public_net:        { get_param: public_net }  
          admin_net:         { get_param: admin_net }
          admin_subnet:      { get_param: admin_subnet }
          manager_ip:        { get_param: manager_ip }
  mon:
    type: lib/managed_linux_server.yaml
    properties:
          key_name:          { get_param: key_name }
          server_name:       mon
          image:             { get_param: image_linux }  
          flavor:            m1.tiny
          sec_group_linux:   { get_param: sec_group_linux }  
          public_net:        { get_param: public_net }  
          admin_net:         { get_param: admin_net }
          admin_subnet:      { get_param: admin_subnet }
          manager_ip:        { get_param: manager_ip }

  dc1:
    type: lib/managed_windows_server.yaml
    properties:
          key_name:          { get_param: key_name }
          server_name:       dc1
          image:             { get_param: image_windows_server }
          flavor:            m1.small
          sec_group_windows: { get_param: sec_group_windows_server }
          public_net:        { get_param: public_net }
          admin_net:         { get_param: admin_net }
          admin_subnet:      { get_param: admin_subnet }
          manager_ip:        { get_param: manager_ip }
  dc2:
    type: lib/managed_windows_server.yaml
    properties:
          key_name:          { get_param: key_name }
          server_name:       dc2
          image:             { get_param: image_windows_server }
          flavor:            m1.small
          sec_group_windows: { get_param: sec_group_windows_server }
          public_net:        { get_param: public_net }
          admin_net:         { get_param: admin_net }
          admin_subnet:      { get_param: admin_subnet }
          manager_ip:        { get_param: manager_ip }
  srv1:
    type: lib/managed_windows_server_two_vols.yaml
    properties:
          key_name:          { get_param: key_name }
          server_name:       srv1
          image:             { get_param: image_windows_server }
          flavor:            m1.small
          sec_group_windows: { get_param: sec_group_windows_server }
          public_net:        { get_param: public_net }
          admin_net:         { get_param: admin_net }
          admin_subnet:      { get_param: admin_subnet }
          manager_ip:        { get_param: manager_ip }

  srv2:
    type: lib/managed_windows_server_two_vols.yaml
    properties:
          key_name:          { get_param: key_name }
          server_name:       srv2
          image:             { get_param: image_windows_server }
          flavor:            m1.small
          sec_group_windows: { get_param: sec_group_windows_server }
          public_net:        { get_param: public_net }
          admin_net:         { get_param: admin_net }
          admin_subnet:      { get_param: admin_subnet }
          manager_ip:        { get_param: manager_ip }


  cl1:
    type: lib/managed_windows_server.yaml
    properties:
          key_name:          { get_param: key_name }
          server_name:       cl1
          image:             { get_param: image_windows_client }
          flavor:            m1.small
          sec_group_windows: { get_param: sec_group_windows_client }
          public_net:        { get_param: public_net }
          admin_net:         { get_param: admin_net }
          admin_subnet:      { get_param: admin_subnet }
          manager_ip:        { get_param: manager_ip }
